### ISSUE TITLE
Recreate Figure 2.3 of Gaos thesis

### ISSUE THREAD

**Issue by fstap** [FaustinCarter/barmat#3]
Hi,
I cannot recreate figure 2.3 of Gaos thesis (http://web.physics.ucsb.edu/~bmazin/Papers/2008/Gao/Caltech%20Thesis%202008%20Gao.pdf) after several attempts. Is it possible that the calculation for the surface impedance is flawed? Maybe I am lucky although this project is pretty old, it would help immensely!

**Comment by FaustinCarter** [comment]
Hi @fstap, what version of python are you using? This code has not yet been ported to python 3. Can you post your code attempt in the comments here? Or did you just try to run the jupyter notebook? I'm happy to help you work through the bugs. The code is pretty old, but I've been meaning to give it some maintenance, so this is as good a reason as any!

The caveats on installation are almost certainly no longer true as both Anaconda and conda-forge have made significant improvements in the way they build numpy for various Windows processors and architectures.

It's also worth mentioning that there are a lot of numerical "gotchas" in this code base that I haven't substantially sorted out yet, which cause strange artifacts to appear. That being said, I've been meaning to convert this codebase to python 3 compatibility for awhile, so I'll try and push a fix for that up soon.

**Comment by fstap** [comment]
I found my mistake, miscalculation on my side! I can create it pretty accurately now.

**Comment by fstap** [comment]
@FaustinCarter Wow, thank you so much for the answer! I am actually using Python 2.7 so I don't have to port the code and I can now accurately recreate the figures of Gao and also figures for YBCO from https://link.springer.com/content/pdf/10.1007/s10948-012-1695-x.pdf and other papers. So this is a huge step as I am trying to model the parameters of YBCO in its superconducting state for an accurate CST simulation. But one question remains: as I am only an engineer who is not that intimate with the physics, is it possible to correct for the thickness of the conductor? The mean free path length of YBCO is only a couple of nm, the conductor thickness is around 150nm. I guess it only makes a small difference but I am not quite sure

**Comment by FaustinCarter** [comment]
> I found my mistake, miscalculation on my side! I can create it pretty accurately now.

That's great, because I ported it to python 3 just now and  I'm getting all sorts of numerical nonsense (things that should be subtracting to zero that aren't) that is almost certainly related to some kind of BLAS implementation issues. So I guess if it is working for you, don't mess with it for now!

**Comment by FaustinCarter** [comment]
> is it possible to correct for the thickness of the conductor?

It is possible in principle, but this code-base doesn't implement the thin-film corrections from Gao's thesis. I wrote this during the tail end of my post-doc and never found the time to implement the non-bulk case, and in my new job I haven't had to think about it at all.

I'm not sure I can promise implementation of that at all, but I think there is probably a reasonable heuristic you could use to estimate it by weighting the value against the penetration depth or something. I'm also not totally sure what bulk/thin-film even means for YBCO since my vague understanding of that material is that the superconductivity isn't really a bulk process but is somehow only present in 2-D sheets or something? (If that sounds dumb it's because I really don't know anything about YBCO!)

**Comment by FaustinCarter** [comment]
I looked at the paper you referenced, and found the expression I was looking for!

![image](https://user-images.githubusercontent.com/10946756/121564663-8f549e00-c9d0-11eb-81e1-ff1a8801a072.png)

That gives you a reasonable way to convert the bulk value to a thin film approximation using the penetration depth.

**Comment by fstap** [comment]
>I'm also not totally sure what bulk/thin-film even means for YBCO since my vague understanding of that material is that the superconductivity isn't really a bulk process but is somehow only present in 2-D sheets or something? 

You are exactly right, the conducting layers in YBCO are CuO2 planes, seperated by Yttrium atoms. But a thin film approximation should be sufficient.
>I looked at the paper you referenced, and found the expression I was looking for!

Thank you so much, I completely missed that equation! I guess its time to call it a day 😅
